# Generated by Django 4.1 on 2022-08-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='approval_status',
            new_name='APPROVAL_STATUS',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_manager',
            new_name='ASSIGNED_MANAGER',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='CREATED_DATE',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_time',
            new_name='END_TIME',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_time',
            new_name='START_TIME',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='TASK_DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='TASK_ID',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='TASK_NAME',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='TASK_STATUS',
        ),
    ]
