# Generated by Django 4.1 on 2022-08-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_approval_status_task_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULL_NAME', models.CharField(max_length=100)),
                ('USER_NAME', models.CharField(max_length=100)),
                ('USER_ID', models.CharField(max_length=100)),
                ('IS_SUPERUSER', models.CharField(max_length=100)),
                ('DEPARTMENT', models.CharField(max_length=100)),
                ('DESIGNATION', models.CharField(max_length=100)),
            ],
        ),
    ]
