# Generated by Django 4.0.6 on 2022-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='TASK_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
