# Generated by Django 4.0.6 on 2022-08-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_task_id_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='APPROVAL_STATUS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
